export const SET_ERROR = "SET_ERROR";
export const SET_USER = "SET_USER";
export const SET_ACCESSTOKEN = "SET_ACCESSTOKEN";
export const SET_STATUSCODE = "SET_STATUSCODE";
export const SET_APPLICATION = "SET_APPLICATION";
export const SET_SUCCESS = "SET_SUCCESS";
export const ACTIVATE_LOADING = "ACTIVATE_LOADING";
export const DEACTIVATE_LOADING = "DEACTIVATE_LOADING";
