export const SET_ROLE = "SET_ROLE";
export const SET_ERROR = "SET_ERROR";
export const SET_USER = "SET_USER";
export const SET_ACCESSTOKEN = "SET_ACCESSTOKEN";
export const SET_STATUSCODE = "SET_STATUSCODE";
export const SET_APPLICATION = "SET_APPLICATION";
export const SET_LOAN = "SET_LOAN";
export const SET_SUCCESS = "SET_SUCCESS";
export const SET_ENCRYPTED_CUSTOMER_DATA = "SET_ENCRYPTED_CUSTOMER_DATA";


export const REMOVE_LOCALSTORAGE_FORM = "REMOVE_LOCALSTORAGE_FORM";
export const SAVE_LOCALSTORAGE_FORM = "SAVE_LOCALSTORAGE_FORM";
export const RESTORE_LOCALSTORAGE_FORM = "RESTORE_LOCALSTORAGE_FORM";
export const SET_PRODUCT_CREDITSCORE = "SET_PRODUCT_CREDITSCORE";
export const SET_APPLICATION_NUMBER = "SET_APPLICATION_NUMBER";
export const ACTIVATE_LOADING = "ACTIVATE_LOADING";
export const DEACTIVATE_LOADING = "DEACTIVATE_LOADING";
export const LOGOUT = "LOGOUT";
export const SET_MAIN_AND_SUB_REASONS = "SET_MAIN_AND_SUB_REASONS";
